version: '3'
tasks:
  default:
    desc: Run tests and linting
    cmds:
      - task: lint-fix
      - task: test

  check:
    deps:
      - lint
      - test

  test:
    desc: Run tests
    cmds:
      - go test -race -v ./...

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run

  lint-fix:
    desc: Run golangci-lint with auto-fix
    cmds:
      - golangci-lint run --fix
